name: Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.22'
      - name: Build
        run: make build
      - name: Archive
        uses: actions/upload-artifact@v3
        with:
          name: git-go-assist
          path: bin/git-go-assist
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          files: bin/git-go-assist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
